# Generated by Django 3.1 on 2020-08-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prozessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serie', models.CharField(max_length=100)),
                ('Modell', models.CharField(max_length=100)),
                ('Codename', models.CharField(max_length=100)),
                ('Kerne', models.FloatField()),
                ('Threads', models.FloatField()),
                ('Prozessortakt', models.FloatField()),
                ('Turbotakt', models.FloatField()),
                ('Sockel', models.CharField(max_length=50)),
                ('TDP', models.CharField(max_length=10)),
            ],
        ),
    ]
