# Generated by Django 3.1 on 2020-08-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc_shop', '0003_auto_20200817_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prozessor',
            name='Codename',
        ),
        migrations.RemoveField(
            model_name='prozessor',
            name='Sockel',
        ),
        migrations.RemoveField(
            model_name='prozessor',
            name='TDP',
        ),
        migrations.RemoveField(
            model_name='prozessor',
            name='Turbotakt',
        ),
    ]
