# Generated by Django 3.1 on 2020-08-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_shop', '0004_auto_20200828_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bestellung',
            fields=[
                ('BestellNummer', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Anzahl', models.IntegerField()),
                ('Prozessor', models.ManyToManyField(to='pc_shop.Prozessor')),
            ],
        ),
    ]
