# Generated by Django 3.1 on 2020-08-28 14:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pc_shop', '0005_bestellung'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bestellung',
            options={'ordering': ['Bestellnummer']},
        ),
        migrations.RenameField(
            model_name='bestellung',
            old_name='BestellNummer',
            new_name='Bestellnummer',
        ),
        migrations.RemoveField(
            model_name='bestellung',
            name='Anzahl',
        ),
        migrations.RemoveField(
            model_name='bestellung',
            name='Prozessor',
        ),
        migrations.RemoveField(
            model_name='prozessor',
            name='id',
        ),
        migrations.AddField(
            model_name='bestellung',
            name='Datum',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prozessor',
            name='Artikelnummer',
            field=models.CharField(default=datetime.datetime(2020, 8, 28, 14, 42, 23, 179723, tzinfo=utc), max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Bestellung_Produkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anzahl', models.IntegerField()),
                ('Artikelnummer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_shop.prozessor')),
                ('Bestellnummer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_shop.bestellung')),
            ],
            options={
                'ordering': ['Bestellnummer'],
            },
        ),
    ]
